### ISSUE TITLE
Add gyroscope deadzone/sensitivity adjustment support

### ISSUE THREAD

**Issue by and-boiko** [FrogTheFrog/steam-gyro-for-cemuhook#4] opened 2018-01-08 23:32 UTC
When I hold the controller steadily, it registers micromovements that result in camera jitter while aiming in BotW on Z axis. Even if I place the controller on a flat surface, it still jitters for 5 seconds until it stops sending input.

**Comment by FrogTheFrog** [comment] 2018-01-09 01:10
I'll push a threshold feature tomorrow. Already tested it and it works like a charm for me, just need to finish something.

However, if you feel a slight drift around one axis (forgot which) keep in mind that I can not eliminate it. It's due to Steam controller having a 6-axis sensor where a 9-axis sensor is required to determine a an absolute value for that one axis. Without an absolute value, it cannot "wiggle" current value back to it. However, it seems that other data is enough to keep that one axis from drifting too far away.

**Comment by FrogTheFrog** [comment] 2018-01-09 15:25
@Bullsquid Try 1.2.0 out. Default values are good enough for me, but you can increase them if you want.

**Comment by and-boiko** [comment] 2018-01-09 22:21
@FrogTheFrog Tried 1.2.0. Played with the values for a couple of days (in-game days), and found these to be the most balanced between jitter and precision:
```
        "accelerometer": {
            "x": 0.01,
            "y": 0.018,
            "z": 0.02
        },
        "gyro": {
            "x": 0,
            "y": 0,
            "z": 0
        }
```

I've set gyro to 0 because otherwise it causes axis drift, and besides, it looks like it doesn't affect jitter much anyway. As for the accelerometer, with the default values I've still experienced "up and down" jitter while aiming, so I had to increase them. I didn't want to set the values too high, because then aim precision drops significantly.

My values work best when the controller is parallel to the floor. If it's tilted up, like it's almost parallel to the screen, it begins to jitter, because sensor axes are now "the wrong way" and my `x` is low for better aiming precision.

**Comment by FrogTheFrog** [comment] 2018-01-09 22:36
So, would you recommend setting default values to your values?

**Comment by and-boiko** [comment] 2018-01-09 22:51
I would recommend setting gyro to 0.

Not sure about accelerometer values, I think it needs more testing with different users. Maybe not all Steam Controllers accelerometer sensors are equal? I find these values good for me, but don't think they're perfect.

**Comment by FrogTheFrog** [comment] 2018-01-09 22:54
I'll just set them all to zero and add some comment about your values to README. I'll close this issue when it's done.

**Comment by and-boiko** [comment] 2018-01-09 23:02
Could the precision drop with high threshold values be combated somehow? Maybe something similar to controller stick deadzone would work: if the deadzone is 25, and the stick is moved past the deadzone to 26, it would send 1 instead of 26. Not sure if it will mess the data up though...

**Comment by FrogTheFrog** [comment] 2018-01-09 23:13
Basically, given that `realValue > thresholdValue`, `finalValue = realValue - thresholdValue`? If yes, then I'll try it tomorrow.

**Comment by and-boiko** [comment] 2018-01-09 23:28
Basically yes, but that way maximum value will be reduced by thresholdValue. Should be `finalValue = maxValue * (realValue - thresholdValue) / (maxValue - thresholdValue)`.

**Comment by and-boiko** [comment] 2018-01-10 09:46
As I'm not sure about the deadzone being a good solution, I've googled a bit and found out that maybe what we need is a low-pass filter to smooth out the data.

There are simple implementations, like using the average of previous data, but this will create some latency and it's not the best low-pass you can get, so maybe you can find something better. 
https://stackoverflow.com/questions/4611599/smoothing-data-from-a-sensor

**Comment by FrogTheFrog** [comment] 2018-01-10 11:53
@Bullsquid Deadzone wasn't any different from previous attempt. However, a very simple low-pass filter seems to work... maybe.

Could you contact me on discord (FrogTheFrog#1801)? I would like to send you a test version, before I publish another "broken" one :)

**Comment by Barborica-Alexandru** [comment] 2018-01-21 13:50
Hey. Thanks for all your hard work, I can confirm this issue and also that y threshold set to 0.018 does slightly alleviate the problem. However a deadzone method might be better advised as through all my tweaking the threshold vs post-scaler I was unable to find a balance between shaking and accuracy. Removing the shaking by upping the threshold leads to the crosshair moving in increments instead of smoothly and lowering the post-scaler farther than 0.5 causes the crosshair to move smoothly but rubber band back to its initial position.

**Comment by FrogTheFrog** [comment] 2018-01-21 14:50
@Barborica-Alexandru My "cut off" approach was flawed in v1.2.0. Values must be filtered to reduce stutter, however this produces a side effect - latency. It feels strange at first, but you can get used to it.

I've added filter concept in `test` branch, however "settings" UI is broken at the moment due to Electron using chromium v59. Thus I'm not publishing anything till it is updated to v63+ (https://github.com/electron/electron/pull/11459).

If you want you can build test branch yourself. If you do that, I'll explain what to set in configuration file to enable low-pass filter.

**Comment by and-boiko** [comment] 2018-01-21 20:07
Since I'm having troubles with building the project and don't currently have time to do this myself, I maybe just publish my idea here for someone to implement:
Take v1.2.0 approach with threshold, but once a threshold has been hit, set threshold to 0 for the next n cycles (for example, something around 0.5-1 second). This way the moment you start moving gyro significantly, you get 100% precision until you stop moving (when the changes are lower than threshold). Then, you get jitters for just about a second and precision returns back to "low", so you get stable camera until you move the controller again.

Something like this in pseudo-code (only for x value for simplicity):

```javascript
let highPrecisionCycles = 0;
const NUMBER_OF_CYCLES = 60;
const THRESHOLD = 0.018

function handleChanges(changes) {
  let currentThreshold = THRESHOLD;

  if(Math.abs(changes.x) > THRESHOLD) {
    highPrecisionCycles = NUMBER_OF_CYCLES; // enter "high precision mode" for N cycles
  }

  if(highPrecisionCycles > 0) {
    currentThreshold = 0; // set 100% precision to remove "incremental crosshair" 
    highPrecisionCycles--;
  }

  if(Math.abs(changes.x) > currentThreshold) {
    value.x += changes.x;
  }
}
```

**Comment by FrogTheFrog** [comment] 2018-01-21 23:19
@Bullsquid, @Barborica-Alexandru I've build a pre-release for you. Keep in mind that `settings` UI page is completely broken. You'll have to manually edit generated `json` file.

Here's a little info on how to edit this `json` file (edit with something else than notepad). Delete current `steam-gyro.json` file (backup it first if you want). You'll end up with newly generated file: 
```
{
    "server": {
        "address": "127.0.0.1",
        "port": 26760
    },
    "modifierVersion": 0,
    "enabledFilters": {
        "gyro": false,
        "accelerometer": false
    },
    "silentErrors": false,
    "filters": {
        "gyro": [],
        "accelerometer": []
    }
}
```
Enable filter(-s) by editing `enabledFilters` value.
You can add and chain multiple filters to `filters.gyro` or `filters.accelerometer`. For example:
```
"filters": {
    "gyro": [
         filter1,
         filter2
     ],
     "accelerometer": [
         filter3
     ]
}
```
Here, `filterN` must be of this type/structure:

```
{
    //possible values: "None", "Hysteresis", "Low-pass"
    "type": string, 
    
    //if TRUE then apply filter to x, y, z even if only one of these 3 axis is inside deviation range
    "filterAllAtOnce": boolean,

    //a difference from previous value must fall inside [min; max] (I call it "deviation") range in order to 
    //apply a filter. If this condition is not met, it is skipped
    "deviation": {
        "min": number, //0 is minimum for both gyro and accelerometer
        "max": number, //2 is maximum for accelerometer and 2000 maximum for gyro 

        //use provided data to check against "deviation" range. For gyro it is accelerometer's initial data
        //for accelerometer it is gyro's initial data (initial = before filtering)
        "useProvidedData": boolean
    },

    //various coefficients used by filter
    "coefficients": number[]
}
```
Filter `None` does nothing. 
Filter `Hysteresis` is the @Bullsquid's "threshold" filter (just wanted a fancy name). You **MUST** provide at least 2 coefficients for it, otherwise it will throw an error. For example:
```
"coefficients": [
    0.018  //inner threshold,
    1000000 //time (in microseconds) to activate "100% precision" mode for
]
```
Filter `Low-pass` is a [low-pass](https://en.wikipedia.org/wiki/Low-pass_filter) filter. You **MUST** provide at least 1 coefficient for it, otherwise it will throw an error. For example:
```
"coefficients": [
    0.07  //alpha value
]
```

## Examples
### @Bullsquid's filter for accelerometer
```
{
    "server": {
        "address": "127.0.0.1",
        "port": 26760
    },
    "modifierVersion": 0,
    "enabledFilters": {
        "gyro": false,
        "accelerometer": true
    },
    "silentErrors": false,
    "filters": {
        "gyro": [],
        "accelerometer": [
            {
                "type": "Hysteresis",
                "filterAllAtOnce": false,
                "deviation": {
                    "min": 0,
                    "max": 2,
                    "useProvidedData": false
                },
                "coefficients": [
                    0.018
                    1000000
                ]
            }
        ]
    }
}
```

## A low-pass accelerometer filter based on gyro's data
I find this filter quite interesting and might be worth it to play with `max` value or `coefficient` value.
```
{
    "server": {
        "address": "127.0.0.1",
        "port": 26760
    },
    "modifierVersion": 0,
    "enabledFilters": {
        "gyro": false,
        "accelerometer": true
    },
    "silentErrors": false,
    "filters": {
        "gyro": [],
        "accelerometer": [
            {
                "type": "Low-pass",
                "filterAllAtOnce": false,
                "deviation": {
                    "min": 0,
                    "max": 0.5,
                    "useProvidedData": true
                },
                "coefficients": [
                    0.07
                ]
            }
        ]
    }
}
```

**Comment by Bullsquid** [comment] 2018-01-21 23:29
@FrogTheFrog I believe the first example should have "Hysteresis" type.

**Comment by Barborica-Alexandru** [comment] 2018-01-22 12:08
There is a syntax error somewhere here and I can't seem to find it:
```
{
    "server": {
        "address": "127.0.0.1",
        "port": 26760
    },
    "modifierVersion": 0,
    "enabledFilters": {
        "gyro": false,
        "accelerometer": true
    },
    "silentErrors": false,
    "filters": {
        "gyro": [],
        "accelerometer": [
		    {
                "type": "Hysteresis",
                "filterAllAtOnce": false,
                "deviation": {
                    "min": 0,
                    "max": 2,
                    "useProvidedData": false
                },
                "coefficients": [
                    0.018
                    1000000
                ]
            }
		]
    }
}
```

Error log
```
2018-01-22T12:06:49.010Z - error: FATAL ERROR!
2018-01-22T12:06:49.011Z - error:  SyntaxError: Unexpected number in JSON at position 603
    at JSON.parse (<anonymous>)
    at __WEBPACK_IMPORTED_MODULE_0_fs_extra__.readFile (C:\Users\Alex\AppData\Local\Temp\nsqC181.tmp\app\resources\app.asar\dist\main.bundle.js:1828:51)
    at C:\Users\Alex\AppData\Local\Temp\nsqC181.tmp\app\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
2018-01-22T12:06:58.361Z - error: FATAL ERROR!
2018-01-22T12:06:58.362Z - error:  SyntaxError: Unexpected number in JSON at position 603
    at JSON.parse (<anonymous>)
    at __WEBPACK_IMPORTED_MODULE_0_fs_extra__.readFile (C:\Users\Alex\AppData\Local\Temp\nsqE65F.tmp\app\resources\app.asar\dist\main.bundle.js:1828:51)
    at C:\Users\Alex\AppData\Local\Temp\nsqE65F.tmp\app\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

I don't know why breaks don't appear in `code`


EDIT: Found it. "," missing after first coeficient for hysteresis.

**Comment by FrogTheFrog** [comment] 2018-01-22 12:21
Use "```" for code blocks instead of "`".

**Comment by Barborica-Alexandru** [comment] 2018-01-22 12:39
Ok so I tested it out. Hysteresis does not work but we knew that already from the previous implementation as it is essentially the same.

However the low-pass filter based on the gyro data is AMAZING. Out of the box values you provided and the experience is almost exactly what it should be. Some more tweaking might be required but for the next release I recommend this as the default.

**Comment by FrogTheFrog** [comment] 2018-01-22 17:16
@Barborica-Alexandru If you find almost perfect settings, could you post them here? I personally like:
```
{
    "type": "Low-pass",
    "filterAllAtOnce": false,
    "deviation": {
        "min": 0,
        "max": 0.8,
        "useProvidedData": true
    },
    "coefficients": [
        0.07
    ]
}
```
but I'm open for a debate.

**Comment by Barborica-Alexandru** [comment] 2018-01-22 19:16
I settled on 
```
{
    "server": {
        "address": "127.0.0.1",
        "port": 26760
    },
    "modifierVersion": 0,
    "enabledFilters": {
        "gyro": false,
        "accelerometer": true
    },
    "silentErrors": false,
    "filters": {
        "gyro": [],
        "accelerometer": [
		    {
                "type": "Low-pass",
                "filterAllAtOnce": false,
                "deviation": {
                    "min": 0,
                    "max": 0.7,
                    "useProvidedData": true
                },
                "coefficients": [
                    0.06
                ]
            }
		]
    }
}
```

Variation might exist between controllers so I don't know if almost perfect settings even exist but for me the algorithm itself is such a major improvement that between my settings and yours the difference is quite minimal. It's more about personal preference.

**Comment by FrogTheFrog** [comment] 2018-01-23 20:34
@Bullsquid What do you think?

**Comment by and-boiko** [comment] 2018-01-23 22:18
@FrogTheFrog Didn't have time to try the new version yet, sorry. :(

**Comment by and-boiko** [comment] 2018-01-26 22:58
I've finally tested it and I couldn't get anything better than @Barborica-Alexandru's settings.

It's really hard to set it, because you have to constantly battle jitter, precision, drag and latency. Hysteresis is pointless with all the axis sharing the same value, because in previous version only one of them needed to be high.

Working GUI would help a lot with trying out new settings, because I really got tired of editing JSON and restarting the server.

Although these settings aren't _perfect_ for me (still shakes a little, but you can get used to it), I think it's okay to make these default unless we find something better. Too bad I don't have any ideas and am not an expert in gyro/accelerometer data smoothing.

**Comment by FrogTheFrog** [comment] 2019-02-07 14:08
Added realtime filter support with low-pass filter for accelerometer and high-pass filter for gyro. Might add more filters later on (PRs are also welcome), however I'm closing this for now.

**Closed as completed by FrogTheFrog** 2019-02-07 14:08 UTC
