### ISSUE TITLE
Lagging haptics and controller rumble gets stuck

### ISSUE THREAD

**Issue by ajojoreference** [FrogTheFrog/steam-gyro-for-cemuhook#7] opened 2018-03-14 21:14 UTC
Whenever the tool is open, the controller will just skip over some of the haptics for each input. This is most noticeable with the right pad's haptics. In addition, the emulated rumble will always get stuck whenever the controller is supposed to vibrate. Changing the rumble frequency setting does nothing to solve this. This happens across all games.

**Comment by FrogTheFrog** [comment] 2018-03-14 22:29
When this app is closed everything works as intended?

**Comment by ajojoreference** [comment] 2018-03-15 01:45
Yep, the controller works perfectly as soon as I close the app.

**Comment by FrogTheFrog** [comment] 2018-03-15 01:58
What game should be easy to replicate this problem with? I personally hate rumble, so I have it turned of by default.

**Comment by ajojoreference** [comment] 2018-03-15 20:51
I can confirm it tends to happen whenever you fire your gun in splatoon. Tested this using the practice mode for the gun you start the game with. Also the treasure tracker levels in SM3DWorld have the rumble get stuck whenever toad enters a door or falls down, I tested this using the world 5 treasure tracker level near the end.

**Comment by kmicki** [comment] 2018-04-04 11:20
Indeed haptics feel different when the tool is running. You can feel the difference on default desktop config when using right trackpad - it seems to skip some.
About rumble emulation - whenever there should be a long rumble, I only get very weak, short shake.
Without the tool running haptis and rumble work properly.

**Comment by FrogTheFrog** [comment] 2018-04-04 22:53
@ajojoreference, @kmicki Just letting you know that I've found out what causes it, unfortunately I'm very busy this week. I'll try to push a fix this weekend.

**Comment by FrogTheFrog** [comment] 2018-04-06 12:49
@ajojoreference, @kmicki What APP version are you using? I was planning on releasing final `1.3.0` version, but I think I won't make it. However, I can add a hotfix to current `1.2.0` or `1.3.0` builds.

**Comment by ajojoreference** [comment] 2018-04-06 16:07
I'm using the 1.3.0 pre-release version.

**Comment by kmicki** [comment] 2018-04-06 16:57
I'm also using 1.3.0. Thank you!

**Comment by FrogTheFrog** [comment] 2018-04-06 17:38
The reason rumble and haptics (did not test this, but I assume it should work properly now) were acting weird is because I check if sensor's data is "stuck". If it is, then I send a request to Steam Controller to enable sensors. This request is the cause of all this nonsense. Checking if sensor's data is "stuck" is basically a guesswork, therefore it gives a lot of false-positives.

I managed to reduce these false-positives by doing guesswork on 200 sequential data packages I receive from controller (basically counting up to 200). If I determine that data is "stuck", I send a request to controller. If any of the received packages says that data isn't "stuck", I reset counter and repeat the process.

200 should be enough, however if it's not - tell me and I'll increase it.

P.S. could you confirm that haptics are working?

**Comment by FrogTheFrog** [comment] 2018-04-06 17:38
@ajojoreference, @kmicki I've uploaded it now.

**Comment by kmicki** [comment] 2018-04-11 06:43
@FrogTheFrog it is working, thank you.

**Comment by FrogTheFrog** [comment] 2019-02-07 14:09
Should be fixed in final 1.3.0 release.

**Closed as completed by FrogTheFrog** 2019-02-07 14:09 UTC
