### ISSUE TITLE
Cemuhook does not detect gyro or controller (version 1.2.0)

### ISSUE THREAD

**Issue by Shigbeard** [FrogTheFrog/steam-gyro-for-cemuhook#13] opened 2018-08-18 17:28 UTC
steam-gyro version: 1.2.0
Cemu: 1.13.0f
cemuhook: 0.5.6.5
Date last produced: 2018-08-19

Description: Cemuhook does not detect the steam controller or the gyro when selecting gamepad motion source. Instead reads "DISCONNECTED" and does not produce motion in-game. Attempts have not been made to use the pre-release version 1.3.0 (See links below)

Expected behavior: When selecting a motion source, DSU1 should show information about my devices MAC address and allow me to select it.

Images:
[Cemu sceenshot showing "DISCONNECTED" status for all motion sources (imgur.com)](https://i.imgur.com/cD3rKc3.png)
[Windows notification showing that the UDP server was started (imgur.com)](https://i.imgur.com/J5oJTRJ.png)
[Screenshot of Steam Gyro settings page, demonstrating default settings (imgur.com)](https://i.imgur.com/RHOxlRH.png)

**Comment by Shigbeard** [comment] 2018-08-18 17:30
It's also worth noting that the Steam Devices tab produces a loading circle that does not go away ([link](https://i.imgur.com/4VBMGJH.png))

**Comment by Shigbeard** [comment] 2018-08-19 11:20
Update: Appears to be a cemuhook problem, not a Steam Gyro problem. Connection was successful just now, scenario was that the server was running for an extended period of time and cemu was launched through a steam shortcut with the controller turned on.

Needs investigating.

**Comment by ExpatUK** [comment] 2019-01-04 21:04
I can confirm this behaviour on Cemu 15 And 15.1 with both 1.2 and 1.3 versions of this plugin.
It's shame because it's the first thing I've tried to use the gyro with. I'm running cemuhook 0.5.7.0.

**Comment by FrogTheFrog** [comment] 2019-02-07 14:10
@ExpatUK, @Shigbeard sorry for the very late reply. I've finally released v1.3.0, is it still broken?

**Comment by ExpatUK** [comment] 2019-02-08 13:05
I'll test later this evening and let you know - got a DS4 for BOTW and haven't looked back so far. :)

**Comment by ExpatUK** [comment] 2019-02-11 11:47
@FrogTheFrog Hi, sorry for the late response. New version does not even detect controller at desktop - unable to test with CEMU.

**Comment by Scoo** [comment] 2019-02-21 23:55
Hello,
I recently downloaded the last versions of Cemu and Cemuhook, tried to run steam-gyro-for-cemuhook.exe, unfortunately no controller seems to be detected.
Also tried directly on padtest, still nothing...

I'm pretty sure I followed the instructions, because after that I succesfully used my phone's gyro both on padtest and in game.

Is there anything to do about it, like downgrading Cemuhook or something else?
BTW huge thanks for your work!

PS: I just tried versions 1.0.4 and 1.0.5 of your software, controller is detected but javascript error happens as soon as you move it.

**Comment by FrogTheFrog** [comment] 2019-02-22 00:01
@Scoo I and @ExpatUK will try to pinpoint the issue this weekend. Btw, what kind of error do you get for 1.0.4?

**Comment by Scoo** [comment] 2019-02-22 00:10
![errorsteamgyro](https://user-images.githubusercontent.com/1344703/53210572-9d832280-363e-11e9-98d3-274b629eed3f.png)

**Comment by FrogTheFrog** [comment] 2019-02-22 00:17
This error occurs (which is fixed in later versions) because of the issue you're having right now - not connecting to a steam controller.

**Comment by Scoo** [comment] 2019-02-22 10:31
On your 1.1.0 version you added a tab to show different devices.
I see several steam controllers on it, you can take a look here:
![gyrocemu1 1 0](https://user-images.githubusercontent.com/1344703/53236274-2d9f8700-3694-11e9-96b8-5717cba1b796.jpg)

Only the first one is receiving good informations in real time when I hit buttons and move the controller, the other ones seem frozen:
![gyrocemu1 1 0again](https://user-images.githubusercontent.com/1344703/53236507-b3bbcd80-3694-11e9-9c78-c039a23e81a0.jpg)

I hope this will help you finding what is wrong, but I'm still doing some tests in case there is something wrong with my steam controller or its parameters, will let you know...

**Comment by FrogTheFrog** [comment] 2019-10-25 14:04
Closing old issue.

**Closed as completed by FrogTheFrog** 2019-10-25 14:04 UTC
